#!/usr/bin/env python3
"""Turn Menu Intelligence flow output (data/menu-intel/*.json) into InsForge SQL.
Usage: python load_menu_intel.py <dir> <out.sql>"""
import json, sys, glob, os, uuid

def q(s):
    if s is None: return "null"
    return "'" + str(s).replace("'", "''") + "'"

def num(x):
    return "null" if x is None else str(x)

CUISINE_ID = {
    "italian":"italian","american":"american","french":"french","chinese":"chinese",
    "burmese":"burmese","indian":"indian","middle eastern":"middle-eastern",
    "middle-eastern":"middle-eastern","mexican":"mexican",
}

def main(d, out):
    files = sorted(glob.glob(os.path.join(d, "*.json")))
    # Note: no BEGIN/COMMIT — InsForge `db import` manages its own transaction.
    sql = ["-- generated by load_menu_intel.py — Menu Intelligence → InsForge"]
    nrest=nbranch=ndish=ning=0
    for f in files:
        data = json.load(open(f))
        cid = CUISINE_ID.get(data["cuisine"].strip().lower())
        if not cid:
            print("!! unknown cuisine:", data["cuisine"]); continue
        for r in data["restaurants"]:
            rid = str(uuid.uuid4()); nrest+=1
            sql.append(
                f"insert into mi_restaurants (id,cuisine_id,name,rank,website,summary) values "
                f"({q(rid)},{q(cid)},{q(r['name'])},{num(r.get('rank'))},{q(r.get('website'))},{q(r.get('summary'))}) "
                f"on conflict (cuisine_id,name) do nothing;")
            for b in r.get("branches", []):
                sql.append(
                    f"insert into mi_branches (restaurant_id,name,city,region) select id,{q(b.get('name'))},"
                    f"{q(b.get('city'))},{q(b.get('region'))} from mi_restaurants where cuisine_id={q(cid)} and name={q(r['name'])};")
                nbranch+=1
            for dish in r.get("dishes", []):
                did = str(uuid.uuid4()); ndish+=1
                sql.append(
                    f"insert into mi_dishes (id,restaurant_id,name,section,description,price) select {q(did)},id,"
                    f"{q(dish['name'])},{q(dish.get('section'))},{q(dish.get('description'))},{num(dish.get('price'))} "
                    f"from mi_restaurants where cuisine_id={q(cid)} and name={q(r['name'])};")
                seen=set()
                for ing in dish.get("ingredients", []):
                    nm=ing["name"].strip().lower()
                    if nm in seen: continue
                    seen.add(nm)
                    sql.append(
                        f"insert into mi_dish_ingredients (dish_id,ingredient,is_core,derived) values "
                        f"({q(did)},{q(ing['name'])},{str(ing.get('is_core',True)).lower()},{str(ing.get('derived',False)).lower()}) "
                        f"on conflict do nothing;")
                    ning+=1
    open(out,"w").write("\n".join(sql)+"\n")
    print(f"files={len(files)} restaurants={nrest} branches={nbranch} dishes={ndish} ingredients={ning}")
    print("wrote", out)

if __name__=="__main__":
    main(sys.argv[1], sys.argv[2])
